import datetime
import logging

import streamlit as st
from streamlit_chat import message
from api import post


# Private method to add a message to the conversation
def _add(string_value: str, true_if_user: bool,
         time_stamp: datetime.datetime = datetime.datetime.now()):
    # Add message dict to session state
    st.session_state.history.append({'true_if_user': true_if_user,
                                     'message': string_value,
                                     'sent': time_stamp})


# Render the conversation
def render(conversation: list[dict]):
    for i in range(len(conversation)):
        message(message=conversation[i]['message'],
                is_user=conversation[i]['true_if_user'],
                key=str(i))


# Send a message and receive the response generated by the server.
def send_and_process(contents: str):
    logging.info(f"Attempting to send message")
    # Send the message
    response = post.send_message(contents)

    # Check the response
    if response.status_code == 201:
        # Add the messages to the conversation
        _add(contents, True)
        _add(response.json()['answer'], False)
        logging.info(f"Message sent processed successfully")
    else:
        # Print error
        logging.error(f"Error sending message: {response.status_code}")
        st.error("Something went wrong...")
